# This file is machine-generated - editing it directly is not advised

[[ErrorTypes]]
git-tree-sha1 = "e6bb0b15ed83801e07f6b3d3bff2a68692410b69"
uuid = "7f495686-c6d2-4c77-9e8e-e4c865675f9d"
version = "0.4.0"
